Update readme.md
savushkin-r-d/EasyEPLANner pull request #1098
Opened 2022-12-26 08:54 UTC by Vlad-203

2022-12-26 09:45 UTC, KirillGutyrchik commented on docs/ru/readme.md
> -Надстройка EasyEPLANner разработана как Add-In к EPLAN, на данный момент используется версия EPLAN 2.9. Надстройка используется при разработке проектов в EPLAN и позволяет автоматизировать работу инж
"инженера-программиста"  было написано правильно.

2022-12-26 09:46 UTC, KirillGutyrchik commented on docs/ru/readme.md
> +Надстройка EasyEPLANner разработана как Add-In к EPLAN, на данный момент используется версия EPLAN 2.9. Надстройка используется при разработке проектов в EPLAN и позволяет автоматизировать работу инж
Не исправлена пнуктационная ошибка описанная в задаче.

2022-12-26 09:47 UTC, KirillGutyrchik commented on docs/ru/readme.md
>  С помощью EasyEPLANner описываются технологические объекты (Танк, Бойлер и др.), операции этих объектов, шаги операций, устанавливаются ограничения для операций, а так же множество других свойств тех
Не исправлена пунктационная ошибка описанная в задаче.

2022-12-27 07:56 UTC, idzm requested changes

2022-12-27 07:56 UTC, idzm commented on docs/ru/readme.md
> -Надстройка EasyEPLANner разработана как Add-In к EPLAN, на данный момент используется версия EPLAN 2.9. Надстройка используется при разработке проектов в EPLAN и позволяет автоматизировать работу инж
Здесь не исправление имеющейся ошибки, а добавление новой.

2022-12-27 07:57 UTC, idzm requested changes

2022-12-27 07:57 UTC, idzm commented on docs/ru/readme.md
> +Надстройка EasyEPLANner разработана как Add-In к EPLAN, на данный момент используется версия EPLAN 2.9. Надстройка используется при разработке проектов в EPLAN и позволяет автоматизировать работу инж
Здесь не исправление имеющейся ошибки, а добавление новой.

2023-01-03 06:07 UTC, closed without merging