Add Node adress space control
savushkin-r-d/EasyEPLANner pull request #1203
Opened 2023-08-16 08:51 UTC by KirillGutyrchik

Fixes #1202.

2023-08-25 13:58 UTC, idzm commented
@KUZMA-1989, @AndreyNemenkov - какое максимальное количество модулей IO-Link может быть в узле?

2023-08-29 09:17 UTC, AndreyNemenkov commented
> @KUZMA-1989, @AndreyNemenkov - какое максимальное количество модулей IO-Link может быть в узле?

https://www.phoenixcontact.com/en-pc/products/software-project-2988667
В этой программе, можно проверять и составлять шину с любыми модулями, там и ограничения пишет

2023-09-04 07:15 UTC, idzm requested changes

2023-09-04 07:15 UTC, idzm commented on docs/user_manual/ReadMe.md
> +<p align="justify"><b>Адресное пространство узла:</b> узлы имеют ограниченное адресное пространство для подключения модулей, для WAGO - 64, Phoenix Contact - 63. При добавлении модуля превосходящего
```suggestion
<p align="justify"><b>Адресное пространство узла:</b> узлы имеют ограниченное адресное пространство для подключения модулей: для WAGO - 64, Phoenix Contact - 63. При добавлении модуля, превосходящего адресное пространство узла, появляется соответствующая ошибка и модуль не сохраняется в описании.</p>
```

2023-09-07 14:04 UTC, idzm approved these changes

2023-09-07 14:12 UTC, merged