Добавление в русскую версию How to build и блоки кода для клонирования репозитория
savushkin-r-d/EasyEPLANner pull request #1276
Opened 2023-12-07 21:19 UTC by marla124

https://github.com/savushkin-r-d/EasyEPLANner/issues/1275

2023-12-08 05:24 UTC, KirillGutyrchik requested changes
Можно также добавить для [немецкой версии ](https://github.com/savushkin-r-d/EasyEPLANner/tree/master/docs/de/readme.md) файла.

2023-12-08 05:24 UTC, KirillGutyrchik commented on docs/ru/readme.md
> +Поздравляем, теперь вы можете собрать это решение (_если у вас есть EPLAN P8 app_).
```suggestion
Поздравляем, теперь вы можете собрать это решение (_если у вас есть приложение EPLAN P8_).
```

2023-12-08 10:49 UTC, Aveerr commented on docs/ru/readme.md
> +Поздравляем, теперь вы можете собрать это решение (_если у вас есть EPLAN P8 app_).
Добавил для [немецкой версии ](https://github.com/savushkin-r-d/EasyEPLANner/tree/master/docs/de/readme.md) в своём [pull request](https://github.com/savushkin-r-d/EasyEPLANner/pull/1278)

2023-12-11 05:23 UTC, KirillGutyrchik commented
@marla124, для запроса необходимо создать новую ветку и сделать запрос из нее (не из master).

2023-12-11 05:23 UTC, closed without merging