Add new device G
savushkin-r-d/EasyEPLANner pull request #1380
Opened 2024-05-22 09:30 UTC by VadimZezyotkoATP

2024-05-22 09:36 UTC, KirillGutyrchik commented on src/Device/DeviceSubTypeEnum.cs
> +        G_VIRT, ///< Виртуальный блок питания с автоматическим выключателем (без привязки к модулям).
Данные подтипы не нужны
```suggestion
        G_IOL_4, ///< Phoenix Contact 4 канала.
        G_IOL_8, ///< Phoenix Contact 8 каналов.
```

2024-05-22 09:38 UTC, KirillGutyrchik commented on src/Device/DeviceTypeEnum.cs
> +        G, ///< Блок питания с автоматическим выключателем.
Новый тип устройства в перечислении добавляется в конец

2024-05-22 09:40 UTC, KirillGutyrchik commented on src/Device/IODevices/G.cs
> +                case "G_VIRT":
Описать здесь только подтипы G_IOL_4 и G_IOL_8

2024-05-22 09:41 UTC, KirillGutyrchik commented on src/Device/IODevices/G.cs
> +                    break;
Описать сдесь только подтипы G_IOL_4 и G_IOL_8

2024-05-22 09:42 UTC, KirillGutyrchik commented on src/Device/IODevices/G.cs
> +        }
Описать правильно подтипы

2024-05-22 09:43 UTC, KirillGutyrchik commented on src/Device/IODevices/G.cs
> +            bool needCheckArticle = DeviceSubType != DeviceSubType.G_VIRT;
G_VIRT пока что не будет, можно удалить
```suggestion
```

2024-05-22 09:44 UTC, KirillGutyrchik commented on src/Device/IODevices/G.cs
> +                            };
```suggestion
```

2024-05-22 09:45 UTC, KirillGutyrchik requested changes
Нужно добавить тесты ([пример](https://github.com/savushkin-r-d/EasyEPLANner/blob/master/EasyEplanner.Tests/EplanDevice.Test/IODevice.Test/F.Test.cs)).
А также документацию.

2024-05-22 11:11 UTC, KirillGutyrchik commented on src/Device/DeviceSubTypeEnum.cs
>          G_IOL_4, ///< Phoenix Contact 4 канала.
```suggestion
        G_IOL_4 = 1, ///< Phoenix Contact 4 канала.
```

2024-05-22 13:22 UTC, KirillGutyrchik commented on src/Device/DeviceSubTypeEnum.cs
> +        G_IOL_4, ///< Phoenix Contact 4 канала.
```suggestion
        G_IOL_4 = 1, ///< Phoenix Contact 4 канала.
```

2024-06-14 07:01 UTC, idzm approved these changes

2024-06-14 07:16 UTC, KirillGutyrchik approved these changes

2024-06-14 07:23 UTC, merged