Edit manual BLINK tag description
savushkin-r-d/EasyEPLANner pull request #1382
Opened 2024-05-24 08:45 UTC by KirillGutyrchik

Fixes #1381.

2024-05-24 10:37 UTC, SergeiSilakov approved these changes

2024-05-24 10:37 UTC, SergeiSilakov commented on docs/user_manual/ReadMe.md
> +        * BLINK - Индикация местонахождения устройства (по умолчанию мигает фиолетовым цветом);
```suggestion
        * BLINK - Индикация местонахождения устройства (быстро мигающие светодиоды);
```

2024-05-24 10:37 UTC, SergeiSilakov commented on src/Device/Tag.cs
> +            /// Индикация местонахождения устройства (по умолчанию мигает фиолетовым цветом).
```suggestion
            /// Индикация местонахождения устройства.
```

2024-05-24 10:39 UTC, SergeiSilakov requested changes

2024-05-24 10:39 UTC, SergeiSilakov commented on docs/user_manual/ReadMe.md
> +        * BLINK - Индикация местонахождения устройства (по умолчанию мигает фиолетовым цветом);
```suggestion
        * BLINK - Индикация местонахождения устройства (быстро мигающие светодиоды);
```

2024-05-24 10:39 UTC, SergeiSilakov commented on src/Device/Tag.cs
> +            /// Индикация местонахождения устройства (по умолчанию мигает фиолетовым цветом).
```suggestion
            /// Индикация местонахождения устройства.
```

2024-05-27 05:45 UTC, SergeiSilakov approved these changes

2024-05-27 06:44 UTC, idzm commented on docs/user_manual/ReadMe.md
> +        * BLINK - Индикация местонахождения устройства (по умолчанию мигает фиолетовым цветом);
```suggestion
        * BLINK - индикация местонахождения устройства (по умолчанию мигает фиолетовым цветом);
```

2024-05-27 06:45 UTC, idzm requested changes

2024-05-27 06:45 UTC, idzm commented on docs/user_manual/ReadMe.md
> +        * BLINK - Индикация местонахождения устройства (быстро мигающие светодиоды);
```suggestion
        * BLINK - индикация местонахождения устройства (быстро мигающие светодиоды);
```

2024-05-27 06:58 UTC, SergeiSilakov approved these changes

2024-06-04 05:19 UTC, VadimZezyotkoATP approved these changes

2024-06-06 05:25 UTC, idzm approved these changes

2024-06-06 05:31 UTC, merged