Generate Eplan pages with IO-modules importing from main.wago.plua
savushkin-r-d/EasyEPLANner pull request #1417
Opened 2024-08-07 13:49 UTC by KirillGutyrchik

Fixes #1398.

```ChangeLog
Добавлена функциональность, позволяющая импортировать старые проекты из main.wago.plua, генерируя страницы EPLAN с модулями.
```

2024-08-22 13:50 UTC, VadimZezyotkoATP approved these changes

2024-08-23 09:02 UTC, idzm requested changes
Надо убрать данные замечания - https://sonarcloud.io/project/issues?id=savushkin-r-d_EasyEPLANner&pullRequest=1417&issueStatuses=OPEN,CONFIRMED&sinceLeakPeriod=true.

2024-08-23 11:14 UTC, idzm commented on src/Main/ImportIcpWagoModulesAction.cs
> +                // Fix main.wago.plua '}'
А этот комментарий что обозначает?

2024-08-27 12:00 UTC, idzm requested changes

2024-08-29 13:30 UTC, idzm approved these changes

2024-08-29 13:40 UTC, merged