Finished new editor
savushkin-r-d/EasyEPLANner pull request #525
Opened 2020-09-01 08:55 UTC by dimabeel

Fixes #493 

Заместили сохранение из старого редактора, в новый.

2020-09-01 09:01 UTC, dimabeel commented
Экспорт объектов из редактора переделан под новый редактор.

2020-09-02 12:37 UTC, dimabeel commented
Рефакторинг работы с окнами.

2020-09-03 07:41 UTC, dimabeel commented
Добавлен экспорт Excel, генерация базы каналов. Убран старый редактор.

2020-09-04 07:28 UTC, dimabeel commented
Обновлена документация до последней версии. Нужно составить план тестирования и протестировать получившийся результат

2020-09-09 07:04 UTC, dimabeel commented
Вроде как все остальное работает, ошибки были пофикшены. Надо отправлять на ревью и релизить

2020-09-10 07:20 UTC, dimabeel commented
Проявляется ошибка при вырезке неопознанного объекта и вставке его в элемент, который не развернут.

2020-09-10 13:11 UTC, dimabeel commented
Изменили принцип работы. Блокировку объекта убрали т.к она не несёт никакой пользы. Подробнее в документации. Также доработали Ctrl + X (вырезать), убраны баги.

2020-09-11 06:43 UTC, idzm requested changes

2020-09-11 06:43 UTC, idzm commented on docs/user_manual/NewEditor.md
> +<p align="justify">Новый редактор подстроен под модель S-88 рецептурного производства. Мы отошли от универсального объекта и переходим к более уникальным объектам. Появились группы объектов, такие ка
```suggestion
<p align="justify">Новый редактор подстроен под модель S-88 рецептурного производства. Мы отошли от универсального объекта и переходим к более уникальным объектам. Появились группы объектов, такие как: "<em>Ячейка процесса</em>", "<em>Аппарат</em>", "<em>Агрегат</em>". В данный момент все внутренние объекты являются теми же универсальными объектами, которые были в старом дереве. По большей части, изменилось отображение дерева, и дополнена функциональность.</p>
```

2020-09-11 06:43 UTC, idzm commented on docs/user_manual/NewEditor.md
> +<p align="justify">Добавились такие группы, как "<b>Мастер</b>", "<b>Агрегат</b>", "<b>Аппарат</b>". Причем, группа "<b>Мастер</b>" содержит один единственный объект, и не может содержать подтипов. Г
```suggestion
<p align="justify">Добавились такие группы, как "<b>Ячейка процесса</b>", "<b>Агрегат</b>", "<b>Аппарат</b>". Причем, группа "<b>Ячейка процесса</b>" содержит один единственный объект, и не может содержать подтипов. Группы "<b>Агрегат</b>" и "<b>Аппарат</b>" реализуют один тип объектов. Эти группы могут содержать подгруппы, которые будут являться базовыми объектами. Это привело к тому, что пользователю теперь не нужно задавать базовый объект. Он будет задан автоматически.</p>
```

2020-09-11 06:43 UTC, idzm commented on src/TechObject/Base/BaseObjectsManager.cs
> +        /// Получить базовый объект мастера проекта.
```suggestion
        /// Получить базовый объект ячейки процесса проекта.
```

2020-09-11 06:43 UTC, idzm commented on src/TechObject/ObjectsTree/ProcessCell.cs
>      /// Объект ячейки производства (мастера).
```suggestion
    /// Объект ячейки процесса (мастера).
```

2020-09-11 07:00 UTC, idzm approved these changes

2020-09-11 07:00 UTC, merged