Fixed EasyEplanner paragraph orthography in ReadMe
savushkin-r-d/EasyEPLANner pull request #692
Opened 2020-12-26 10:03 UTC by as005408

2020-12-27 06:45 UTC, idzm requested changes

2020-12-27 06:45 UTC, idzm commented on ReadMe.md
> +The EasyEplanner developed as an Add-In to EPLAN 2.9 version. This add-in is used for EPLAN projects and helps you to reduce the work of an Automation engineer and a Software engineer as well.
```suggestion
The EasyEplanner developed as an Add-In to EPLAN 2.9 version. This add-in is being used for EPLAN projects and helps you to reduce the work of an Automation engineer and a Software engineer as well. 
```

2020-12-28 06:22 UTC, dimabeel commented
Бессмысленные изменения. Уже известно из предложения первого об дополнении. Поэтому - The.

2020-12-28 07:15 UTC, dimabeel requested changes

2020-12-28 07:15 UTC, dimabeel commented on ReadMe.md
> +The EasyEplanner developed as an Add-In to EPLAN 2.9 version. This add-in is being used for EPLAN projects and helps you to reduce the work of an Automation engineer and a Software engineer as well.
```suggestion
The EasyEplanner developed as an Add-In to EPLAN 2.9 version. The add-in is being used for EPLAN projects and helps you to reduce the work of an Automation engineer and a Software engineer as well. 
```

2021-01-04 05:22 UTC, dimabeel submitted a review, later dismissed

2021-01-04 05:29 UTC, idzm approved these changes

2021-01-04 05:31 UTC, dimabeel approved these changes

2021-01-04 05:32 UTC, merged