Fixed orthography in ReadMe file
savushkin-r-d/EasyEPLANner pull request #693
Opened 2020-12-26 16:45 UTC by as005407

2020-12-27 06:58 UTC, idzm requested changes

2020-12-27 06:58 UTC, idzm commented on ReadMe.md
> +The EasyEPLANner is developing as an Add-In to EPLAN 2.9 version. The add-in is using for EPLAN projects and helps you to reduce the work of an Automation engineer and a Software engineer as well.
```suggestion
The EasyEPLANner is being developed as an Add-In to EPLAN 2.9 version. The add-in is using for EPLAN projects and helps you to reduce the work of an Automation engineer and a Software engineer as well. 
```

2020-12-28 06:19 UTC, dimabeel requested changes

2020-12-28 06:19 UTC, dimabeel commented on ReadMe.md
> +<img src="docs/user_manual/images/EasyEPLANnerPreview.png">
```suggestion
<img src="docs/user_manual/images/EasyEplannerPreview.png">
```

Сломали картинку.

2020-12-28 06:19 UTC, dimabeel commented on ReadMe.md
> +* Channel in [Slack](https://slack.com) - easyEPLANner.slack.com.
```suggestion
* Channel in [Slack](https://slack.com) - easyeplanner.slack.com.
```
Некорректный адрес задан

2020-12-28 06:19 UTC, dimabeel commented on ReadMe.md
> +* [Google group](https://groups.google.com/forum/#!forum/easyEPLANner);
```suggestion
* [Google group](https://groups.google.com/forum/#!forum/easyeplanner);
```
Сломана ссылка была

2020-12-28 06:36 UTC, dimabeel commented on ReadMe.md
> +* [Google group](https://groups.google.com/forum/#!forum/easyEPLANner);
В принципе, для веба не важно - можно так оставить.

2020-12-28 06:42 UTC, idzm commented on ReadMe.md
> +<img src="docs/user_manual/images/EasyEPLANnerPreview.png">
Можно тогда и картинку переименовать, чтобы ссылка корректная была.

2020-12-28 06:52 UTC, dimabeel commented on ReadMe.md
> +<img src="docs/user_manual/images/EasyEPLANnerPreview.png">
ОК. Переименовать картинку по новому регистру и не принимать регистр, который предложил я. Тогда подойдут правки.

2021-01-04 05:26 UTC, dimabeel approved these changes

2021-01-04 05:28 UTC, idzm approved these changes

2021-01-04 05:28 UTC, merged