Add base steps into PAUSE and STOP state
savushkin-r-d/EasyEPLANner pull request #796
Opened 2021-03-23 12:54 UTC by dimabeel

Fixes #628.

Tasks:
- [ ] Add LuaName field in State class.
- [ ] Block use base step in "Во время операции" step
- [ ] Convert reading and saving State class from indexes to LuaNames (including legacy projects support)
- [ ] Add base state in base functionality
- [ ] Reading first old functionality of state, then new if it exists
- [ ] Possibility to add new states without adding much code

2021-03-24 12:07 UTC, dimabeel commented
About channel base for SCADA: need to replace automatically STEPS -> RUN_STEPS and add new states: PAUSE_STEPS, STOP_STEPS.

2021-03-30 05:23 UTC, idzm requested changes

2021-03-30 05:23 UTC, idzm commented on src/TechObject/TechObjectXMLMaker.cs
> +                        if (cdbxTagView == true)
```suggestion
                        if (cdbxTagView)
```

2021-03-30 05:30 UTC, idzm approved these changes

2021-03-30 05:30 UTC, merged