Add IO-Link signal column
savushkin-r-d/EasyEPLANner pull request #903
Opened 2021-09-06 05:50 UTC by dimabeel

Fixes #902

2021-09-06 09:15 UTC, dimabeel commented
Virtual HLA has to have the same tags creation mechanism as IO-Link, because we can push any type of column

2021-09-07 08:16 UTC, dimabeel commented
Unit-tests cover basic cases. In current state it is enough. Our sequence checker can process wrong sequences and find there right description, but user will get an error message. It's okay for us.

2021-09-08 13:46 UTC, rartem submitted a review, later dismissed

2021-09-13 05:43 UTC, idzm requested changes

2021-09-13 05:43 UTC, idzm commented on docs/user_manual/ReadMe.md
> +    * __SIGNALS_SEQUENCE__ - последовательность сигналов (лампочек) и сирены на сигнальной колонне, начиная с нижнего элемента (_прим., SIGNALS_SEUQENCE='ABGYR'_). **A** - сирена, **B** - синяя лампа
```suggestion
    * __SIGNALS_SEQUENCE__ - последовательность сигналов (лампочек) и сирены на сигнальной колонне, начиная с нижнего элемента (_прим., SIGNALS_SEQUENCE='ABGYR'_). **A** - сирена, **B** - синяя лампа, **G** - зеленая лампа, **Y** - желтая лампа, **R** - красная лампа. **Правила**: дублировать символы нельзя, а длина последовательности должна быть от **1** до **5** символов (_т.е наличие компонента сигнальной колонны - обязательно_).
```

2021-09-14 07:02 UTC, idzm approved these changes

2021-09-14 07:02 UTC, merged