Создание дерева рецептов
savushkin-r-d/EasyEPLANner pull request #944
Opened 2021-11-16 13:55 UTC by AlexandraNovik

Создание списка рецептов, каждый из которых содержит набор параметров, выбираемых из параметров существующих в объектах, и задания их значения по умолчанию.

2021-11-17 05:16 UTC, dimabeel requested changes
1. Форматирование кода нужно привести в порядок
2. Удалить закомментированный код

2021-11-17 05:16 UTC, dimabeel commented on src/ProjectManager.cs
> +                    errStr = string.Empty;
```suggestion
                    errStr = string.Empty;
```

Где-то тут баг. Ошибки сбрасываются предыдущие.

2021-11-18 05:02 UTC, AlexandraNovik commented on src/ProjectManager.cs
> +                    errStr = string.Empty;
Но после загрузки технологических объектов и перед загрузкой ограничений мы тоже обнуляем errStr (строка 116).

2021-11-18 12:11 UTC, dimabeel commented on src/ProjectManager.cs
> +                    errStr = string.Empty;
Оказывается баг повыше будет. Не работает функционал в принципе. Res = 1 возвращает только в 1 единственном случае, когда неправильный путь к файлам проекта. В остальных случаях код обнуляется или все сбрасывается. 

Если удалить main.objects.lua или main.restrictions.lua, то будет видно, что ошибки не появляются, а должны. Такая же ситуация будет и с recipe. Я переделаю, но потом придется тебе мержить изменения

2021-11-18 12:12 UTC, dimabeel requested changes

2021-11-18 12:12 UTC, dimabeel commented on src/FileSavers/ProjectDescriptionSaver.cs
> +        public const string MainRecipesFileName = "recipes.lua";
```suggestion
        public const string MainRecipesFileName = "main.recipes.lua";
```

Я бы предпочел такое.

2021-11-18 12:40 UTC, AlexandraNovik commented on src/FileSavers/ProjectDescriptionSaver.cs
> +        public const string MainRecipesFileName = "recipes.lua";
Ok, все равно сейчас код перебираю, исправлю.

2021-11-18 13:31 UTC, dimabeel commented on src/ProjectManager.cs
> +                    errStr = string.Empty;
Можешь смержить изменения, в #945 переделал загрузку немножко

2021-11-19 05:50 UTC, dimabeel requested changes

2021-11-19 05:50 UTC, dimabeel commented on src/ProjectManager.cs
>                          $"\\{ProjectDescriptionSaver.MainRecipesFileName}");
Нет обработки ошибок

2021-11-29 08:39 UTC, dimabeel requested changes
Из дополнительного: почему бы не попробовать использовать интерполяцию строк? Также, если из правой части известен тип объекта, то лучше использовать var, так читабельнее.

2021-11-29 08:39 UTC, dimabeel commented on src/DFrm.cs
> +
Codestyle нарушен. Лишняя строка пустая

2021-11-29 08:39 UTC, dimabeel commented on src/DFrm.cs
> +
Лишняя пустая строка

2021-11-29 08:39 UTC, dimabeel commented on src/DFrm.cs
> +                        if (intMatch.Length < 2)
Магическое число

2021-11-29 08:39 UTC, dimabeel commented on src/Editor/ITreeViewItem.cs
> +        string CheckedObjects { get; }
Не подписано назначение

2021-11-29 08:39 UTC, dimabeel commented on src/Main/ShowRecipesAction.cs
> +                       // MessageBoxButtons.OK, MessageBoxIcon.Warning);
Закомментированный код

2021-11-29 08:39 UTC, dimabeel commented on src/ProjectManager.cs
> +
Лишняя пустая строка

2021-11-29 08:39 UTC, dimabeel commented on src/ProjectManager.cs
> +
Лишняя пустая строка

2021-11-29 08:39 UTC, dimabeel commented on src/ProjectManager.cs
> +
Не написано назначение

2021-11-29 08:39 UTC, dimabeel commented on src/ProjectManager.cs
> +        private IRecipesManager recipesManager;
Не написано назначение

2021-11-29 08:39 UTC, dimabeel commented on src/RManager/IRecipesManager.cs
> +
Лишняя пустая строка

2021-11-29 08:39 UTC, dimabeel commented on src/RManager/IRecipesManager.cs
> +
Лишняя пустая строка

2021-11-29 08:39 UTC, dimabeel commented on src/RManager/RParam.cs
> +
Лишняя пустая строка

2021-11-29 08:39 UTC, dimabeel commented on src/RManager/RParam.cs
> +
Лишняя пустая строка

2021-11-29 08:39 UTC, dimabeel commented on src/RManager/RParam.cs
> +
Лишняя пустая строка

2021-11-29 08:39 UTC, dimabeel commented on src/RManager/Recipe.cs
> +
Лишняя пустая строка

2021-11-29 08:39 UTC, dimabeel commented on src/RManager/Recipe.cs
> +            if (CheckForDupicateParam(ObjId, ObjParam))
Вынести переменную, и использовать её

2021-11-29 08:39 UTC, dimabeel commented on src/RManager/Recipe.cs
> +                if ((par.ObjID == ObjId) && (par.ObjParam == ObjParam))
Сложное условие. Вынести переменную.

2021-11-29 08:39 UTC, dimabeel commented on src/RManager/Recipe.cs
> +                return new string[] { name, "" };
Желательно использовать string.Empty.

2021-11-29 08:39 UTC, dimabeel commented on src/RManager/Recipe.cs
> +                    if (intMatch.Length < 2)
Магическое число

2021-11-29 08:39 UTC, dimabeel commented on src/RManager/Recipe.cs
> +
Лишние пустые строки

2021-11-29 08:39 UTC, dimabeel commented on src/RManager/Recipe.cs
> +
Лишняя пустая строка

2021-11-29 08:39 UTC, dimabeel commented on src/RManager/Recipe.cs
> +                    if (intMatch.Length < 2)
Магическое число

2021-11-29 08:39 UTC, dimabeel commented on src/RManager/Recipe.cs
> +                    DeleteParam(intMatch[0], intMatch[1]);
По массиву непонятное, какие входные аргументы. Надо попробовать вынести переменную

2021-11-29 08:39 UTC, dimabeel commented on src/RManager/Recipe.cs
> +
Лишняя пустая строка

2021-11-29 08:39 UTC, dimabeel commented on src/RManager/RecipesManger.cs
> +
Лишняя пустая строка

2021-11-29 08:39 UTC, dimabeel commented on src/RManager/RecipesManger.cs
> +
Лишняя пустая строка

2021-11-29 08:39 UTC, dimabeel commented on src/RManager/RecipesManger.cs
> +                if (index <= recipes.Count - 2)
Магическое число

2021-11-29 08:39 UTC, dimabeel commented on src/RecipeFrm.cs
> +            const int wndWmCommand = 35587;
Спрашивали у АСУТП, они это окно не используют?
Это окно доступно во всех версиях EPLAN?

2021-11-29 08:39 UTC, dimabeel commented on src/RecipeFrm.cs
> +            string windowName = "Шаблоны сегментов";
В комментарии "Навигатор комментариев", а тут "Шаблон сегментов". Неоднозначность кода.

2021-11-29 08:39 UTC, dimabeel commented on src/RecipeFrm.cs
> +
Лишняя пустая строка

2021-11-29 08:39 UTC, dimabeel commented on src/RecipeFrm.cs
> +
Лишняя пустая строка

2021-11-29 08:39 UTC, dimabeel commented on src/TechObject/ObjectsTree/UniversalObject/Params.cs
> +
Лишняя пустая строка

2021-11-29 09:16 UTC, AlexandraNovik commented on src/RecipeFrm.cs
> +            const int wndWmCommand = 35587;
У Юры спрашивала, вроде не используют.

2021-11-29 11:03 UTC, AlexandraNovik commented on src/RManager/Recipe.cs
> +                if ((par.ObjID == ObjId) && (par.ObjParam == ObjParam))
ты имеешь в виду сделать вложенное условие if в if? или всю эту проверку присвоить в булевскую переменную?

2021-11-29 11:22 UTC, AlexandraNovik commented on src/RManager/RecipesManger.cs
> +                if (index <= recipes.Count - 2)
здесь не магическое число, а проверка на возможность перемещения элемента вниз по дереву (аналогично методу MoveDown в ModesManager, например)

2021-11-29 11:29 UTC, dimabeel commented on src/RManager/Recipe.cs
> +                if ((par.ObjID == ObjId) && (par.ObjParam == ObjParam))
bool varName = condition1 && condition2
Читабельность лучше у кода будет

2021-11-29 11:31 UTC, dimabeel commented on src/RManager/RecipesManger.cs
> +                if (index <= recipes.Count - 2)
Вот как раз таки поэтому это и магическое число. Без комментариев непонятно, зачем это надо. Нужно дать название понятное, чтобы было понятно, что понимать, что это верх/низ и дальше мы никак не пройдем. 0 и 1 ещё допускаются, а все остальное - это магия :)

2021-11-29 11:31 UTC, dimabeel commented on src/RecipeFrm.cs
> +            const int wndWmCommand = 35587;
Комментарий все равно с ошибкой

2021-11-29 11:37 UTC, dimabeel commented on src/RManager/RecipesManger.cs
> +                if (index <= recipes.Count - 2)
Если оперировать тем фактом, что "Так написано там-то", то это значит, что код был просто скопирован, а если это так, то это дублирование. Это значит, что уже нужно рефакторингом заниматься :)

Хороший код строится не сразу, он получается после нескольких итераций рефакторинга

2021-11-30 09:59 UTC, dimabeel requested changes
Замечание по RecipeFrm: это копия NewEditor. Как я понял, произошло Ctrl + C -> Ctrl + V. Это дублирование кода. Так нельзя. Общий абстрактный класс напрашивается

2021-11-30 09:59 UTC, dimabeel commented on src/TechObject/TechObjectManager.cs
> +                CheckRecipes(treeViewItem as TechObject);
Я бы назвал метод Check по другому. Метод говорит своим названием, что он их проверяет на что-то, а на самом деле, он удаляет.

2021-11-30 09:59 UTC, dimabeel commented on src/TechObject/ObjectsTree/UniversalObject/Params.cs
> +                    TechObjectManager.GetInstance().GetTechObjectN(parentTO);
Не совсем понимаю, почему какой-то маленький объектик Params должен знать так много, и так много делать. Здесь что-то не то.

2021-11-30 09:59 UTC, dimabeel commented on src/RecipeFrm.cs
> +            //const string columnName = "Рецепты";
Комментарий

2021-12-02 09:57 UTC, AlexandraNovik commented
> Замечание по RecipeFrm: это копия NewEditor. Как я понял, произошло Ctrl + C -> Ctrl + V. Это дублирование кода. Так нельзя. Общий абстрактный класс напрашивается

Я так понимаю создавать с общими методами и наследовать?

2021-12-02 10:00 UTC, AlexandraNovik commented on src/TechObject/TechObjectManager.cs
> +                CheckRecipes(treeViewItem as TechObject);
могу назвать так же, как потом вызываю в рецептах : `ClearRecipesByObj(TechObject techObject)`

2021-12-02 12:14 UTC, dimabeel commented on src/TechObject/TechObjectManager.cs
> +                CheckRecipes(treeViewItem as TechObject);
Как по мне, это просто ClearRecipes.

2021-12-02 12:18 UTC, AlexandraNovik commented on src/TechObject/TechObjectManager.cs
> +                CheckRecipes(treeViewItem as TechObject);
Ok

2021-12-02 12:18 UTC, dimabeel commented on src/TechObject/ObjectsTree/UniversalObject/Params.cs
> +                    TechObjectManager.GetInstance().GetTechObjectN(parentTO);
Да, но почему параметр должен сам лезть в рецепты и убирать свое упоминание? Это очень сильное нарушение инкапсуляции, как минимум. Я бы использовал событие. Это было бы интересно, чтобы при добавлении в рецептах объекта и параметров, подписываться на событие параметра "Я удаляюсь". У тебя это сразу убирает этот код из менеджера объектов. Вообще, менеджер объектов ничего не должен знать о рецептах. Рецепты стоят выше объектов, а у тебя - как раз наоборот. Вот это мне не нравится.

2021-12-02 12:21 UTC, dimabeel commented
> > Замечание по RecipeFrm: это копия NewEditor. Как я понял, произошло Ctrl + C -> Ctrl + V. Это дублирование кода. Так нельзя. Общий абстрактный класс напрашивается
> 
> Я так понимаю создавать с общими методами и наследовать?

Все верно. Нужно вынести общие методы, причем вынести их нужно правильно (не забывай про дублирование кода), а потом отнаследовать новые классы и использовать методы класса-родителя. Тем самым, ты получаешь общие методы для двух форм, которые служат разным целям. Соответственно, уникальные методы остаются уникальными, либо переопределяются. Если хочешь через переопределение - то базовый класс нужно пометить абстрактным, чтобы нельзя было сделать ошибку, создать класс, который реализует только частичную функциональность

2021-12-02 12:24 UTC, AlexandraNovik commented on src/TechObject/ObjectsTree/UniversalObject/Params.cs
> +                    TechObjectManager.GetInstance().GetTechObjectN(parentTO);
Спасибо за подсказку, мне эта связка самой не нравилась. Не пришло в голову( получается, что при удалении объекта или параметра в объекте можно создать событие, обработчик которого обращается к менеджеру рецептов.
насколько понимаю, это нужно будет реализовывать в Editor-e технологических объектов?

2021-12-02 12:26 UTC, AlexandraNovik commented
> > > Замечание по RecipeFrm: это копия NewEditor. Как я понял, произошло Ctrl + C -> Ctrl + V. Это дублирование кода. Так нельзя. Общий абстрактный класс напрашивается
> > 
> > 
> > Я так понимаю создавать с общими методами и наследовать?
> 
> Все верно. Нужно вынести общие методы, причем вынести их нужно правильно (не забывай про дублирование кода), а потом отнаследовать новые классы и использовать методы класса-родителя. Тем самым, ты получаешь общие методы для двух форм, которые служат разным целям. Соответственно, уникальные методы остаются уникальными, либо переопределяются. Если хочешь через переопределение - то базовый класс нужно пометить абстрактным, чтобы нельзя было сделать ошибку, создать класс, который реализует только частичную функциональность

Я бы выбрала абстрактный и виртуальные методы.

2021-12-02 12:28 UTC, dimabeel requested changes

2021-12-02 12:28 UTC, dimabeel commented on src/Main/ShowRecipesAction.cs
> +                    // Синхронизация названий модулей и устройств в текущем
Комментарий не по теме

2021-12-02 12:28 UTC, dimabeel commented on src/RManager/RParam.cs
> +                    TechObjectManager.GetInstance().GetTObject(objId);
Почему бы не сохранить ссылку на объект, ведь мы можем по его Id его определить? Кстати, какое поведение будет у кода, если я сделаю перестановку (перемещу объект вниз или вверх), и изменится его глобальный номер т.е Id.

2021-12-02 12:28 UTC, dimabeel commented on src/RManager/RParam.cs
> +                if (intMatch.Length == 2)
Непонятно, что значит 2.

2021-12-02 12:28 UTC, dimabeel commented on src/RManager/Recipe.cs
> +            parameters.RemoveAll(par => par.ObjID == ObjId);
А чем отличается DeleteParam от DeleteParamByObj? У C# есть перегрузка методов. Мне кажется, оно сюда ложится хорошо

2021-12-02 12:28 UTC, dimabeel commented on src/RManager/RecipesManger.cs
> +            {
Ну тут аналогично. Два метода, имеют разные сигнатуры и вызывают разные методы, но делают тоже самое. Можно использовать механизм перегрузки методов.

2021-12-02 12:29 UTC, dimabeel commented
> > > > Замечание по RecipeFrm: это копия NewEditor. Как я понял, произошло Ctrl + C -> Ctrl + V. Это дублирование кода. Так нельзя. Общий абстрактный класс напрашивается
> > > 
> > > 
> > > Я так понимаю создавать с общими методами и наследовать?
> > 
> > 
> > Все верно. Нужно вынести общие методы, причем вынести их нужно правильно (не забывай про дублирование кода), а потом отнаследовать новые классы и использовать методы класса-родителя. Тем самым, ты получаешь общие методы для двух форм, которые служат разным целям. Соответственно, уникальные методы остаются уникальными, либо переопределяются. Если хочешь через переопределение - то базовый класс нужно пометить абстрактным, чтобы нельзя было сделать ошибку, создать класс, который реализует только частичную функциональность
> 
> Я бы выбрала абстрактный и виртуальные методы.

Ну я про это и говорю

2021-12-02 12:31 UTC, dimabeel commented on src/TechObject/ObjectsTree/UniversalObject/Params.cs
> +                    TechObjectManager.GetInstance().GetTechObjectN(parentTO);
Нет. Это реализуется в менеджере объектов, у класса параметров. Потом, при добавлении параметра ты все равно ссылку на объект параметра имеешь, и можно подписаться. Потом параметр при удалении должен инициировать событие, и это событие уже дернет метод-обработчик рецепта.

2021-12-02 12:32 UTC, AlexandraNovik commented on src/RManager/RParam.cs
> +                    TechObjectManager.GetInstance().GetTObject(objId);
ты предлагаешь хранить не индексы объектов/параметров, а ссылки на них?

2021-12-02 12:33 UTC, dimabeel commented on src/TechObject/ObjectsTree/UniversalObject/Params.cs
> +                    TechObjectManager.GetInstance().GetTechObjectN(parentTO);
Идея какая: ты удаляешь параметр, а это объект. У тебя есть ссылка на объект параметра при удалении. Перед тем, как удалить его, вызываешь метод типа Parameter.BeforeDeleting.Invoke() и у всех объектов, которые на него подписались (на метод удаления), будет вызван метод-обработчик. А в методе обработчике можно получить Id параметра, и удалить его упоминание в рецептах

2021-12-02 12:35 UTC, AlexandraNovik commented on src/RManager/Recipe.cs
> +            parameters.RemoveAll(par => par.ObjID == ObjId);
Использовала с разными названиями, чтобы себя не путать (так точно знаю, что и где вызываю)

2021-12-02 12:36 UTC, AlexandraNovik commented on src/RManager/RParam.cs
> +                if (intMatch.Length == 2)
Мне уже казалось, что везде поправила. Исправлю

2021-12-02 12:37 UTC, dimabeel commented on src/RManager/Recipe.cs
> +            parameters.RemoveAll(par => par.ObjID == ObjId);
Это немного неправильно, как по мне. Вводит в заблуждение программиста. Методы должны называться по тому, что они делают, а не как работают. Не забывай, что есть тэги <summary>, которые помогают описать метод, если непонятно, что он делает из кода.

2021-12-02 12:40 UTC, dimabeel commented on src/RManager/RParam.cs
> +                    TechObjectManager.GetInstance().GetTObject(objId);
А почему нет? Если у тебя есть индекс, тебе надо вызывать код поиска по индексу. А если есть ссылка, то ничего не надо. Упрощается код, тебе не надо постоянно получать параметр или объект через GetInstanсу(). Логика причем такова, что когда уничтожается объект технологический или параметры, то они удаляются и в рецептах

2021-12-02 12:40 UTC, dimabeel commented on src/RManager/RParam.cs
> +                    TechObjectManager.GetInstance().GetTObject(objId);
Я стараюсь отходить от того, чтобы повально использовать GetIntance() и др. Очень много мест, где потом надо менять код. Всех их не запомнишь

2021-12-02 12:44 UTC, dimabeel requested changes

2021-12-02 12:44 UTC, dimabeel commented on src/RecipeFrm.cs
> +namespace Editor
А почему пространство имен Editor? Я бы использовал Recipe т.к тут работа только и только с рецептами. Что скажешь?

2022-02-22 12:54 UTC, idzm commented
Закрыто из-за отсутствия активности.

2024-01-23 11:13 UTC, closed without merging