Fixed displaying next step bug.
savushkin-r-d/EasyEPLANner pull request #990
Opened 2022-03-11 12:54 UTC by KirillGutyrchik

#987

2022-03-18 12:55 UTC, idzm requested changes

2022-03-18 12:55 UTC, idzm commented on src/Lua/sys.lua
> +            if time_param_n > 0 or condition ~= nil then
```suggestion
            local condition = value.to_step_if_devices_in_specific_state

            if time_param_n > 0 or condition then
```

2022-03-22 05:30 UTC, idzm requested changes

2022-03-22 05:30 UTC, idzm commented on src/Lua/sys.lua
> +            if time_param_n > 0 or condition then
Эти изменения можно убрать, так как следующий шаг сохраняется отдельно в действии.

2022-03-22 05:30 UTC, idzm commented on src/TechObject/ObjectsTree/UniversalObject/Step.cs
> +
Эти изменения можно убрать, так как следующий шаг сохраняется отдельно в действии.

2022-03-22 05:30 UTC, idzm commented on src/TechObject/ObjectsTree/UniversalObject/Step.cs
> +
Эти изменения можно убрать, так как следующий шаг сохраняется отдельно в действии.

2022-03-24 11:52 UTC, idzm requested changes

2022-03-24 11:52 UTC, idzm commented on src/Lua/sys.lua
> +
Эту строку можно убрать.

2022-03-24 11:52 UTC, idzm commented on src/TechObject/ObjectsTree/UniversalObject/Actions/ActionToStepByCondition.cs
> +                "Переход к шагу", "-1"));
```suggestion
                "Шаг", "-1"));
```

2022-03-24 11:52 UTC, idzm commented on src/TechObject/ObjectsTree/UniversalObject/Actions/ActionToStepByCondition.cs
> +
Можно убрать конечные пробелы.

2022-03-24 11:52 UTC, idzm commented on src/TechObject/ObjectsTree/UniversalObject/Actions/ActionToStepByCondition.cs
> +                foreach ( var parameter in Parameters)
```suggestion
                foreach (var parameter in Parameters)
```

2022-03-24 14:15 UTC, idzm requested changes

2022-03-24 14:15 UTC, idzm commented on EasyEplanner.Tests/TechObject.Test/ObjectsTree.Test/UniversalObject.Test/ActionToStepByCondition.Tests.cs
> +        public void AddParam_NewAction_ChekParameterValue(object val,
```suggestion
        public void AddParam_NewAction_CheсkParameterValue(object val,
```

2022-03-25 09:15 UTC, dimabeel reviewed
Если нормально сохраняется в main.objects и нормально загружается, то ок. В prg.lua этого нет. В Excel тоже такая конкретика вроде как не экспортировалась.

Единственное что, я бы может использовал ObjectProperty, как в обычном Action. Тогда может даже кода меньше будет.

2022-03-25 09:15 UTC, dimabeel commented on src/TechObject/ObjectsTree/UniversalObject/Actions/GroupableAction.cs
> +                return SubActions.Cast<ITreeViewItem>()
Если BaseParameter наследуется от ITreeViewItem то вроде Cast не обязательно. Могу ошибаться

2022-03-25 09:15 UTC, dimabeel commented on src/TechObject/ObjectsTree/UniversalObject/Actions/GroupableAction.cs
> +            parameters = new List<BaseParameter>();
Вообще надо подумать, посмотри ссылки GroupableAction в других Action (наследование). Может быть ActionToStepByCondition должно содержать параметры. Поскольку все. что будет наследоваться от GroupableAction будет содержать next_step_n. Если так надо - ок.

2022-03-25 09:15 UTC, dimabeel commented on src/TechObject/ObjectsTree/UniversalObject/Actions/Action.cs
> +        bool IsFilled { get; }
Введено но нигде не используется

2022-03-25 09:18 UTC, dimabeel commented
И я не вижу изменений в документации

2022-03-25 09:24 UTC, dimabeel commented
Надо ещё проверить методы Replace и Insert в GroupableAction (т.к там параметры). Скорее всего если копировать и вставлять, потом заменять -> не будут копироваться значения

2022-03-25 11:19 UTC, KirillGutyrchik commented on src/TechObject/ObjectsTree/UniversalObject/Actions/Action.cs
> +        bool IsFilled { get; }
Было в реализации, но не было в интерфейсе. Добавил, чтобы можно было вызвать из IAction.

2022-03-29 09:30 UTC, KirillGutyrchik commented on src/TechObject/ObjectsTree/UniversalObject/Actions/GroupableAction.cs
> +                return SubActions.Cast<ITreeViewItem>()
Cast тут только для SubActions и неявное для него преобразование запрещено.

2022-03-29 09:33 UTC, KirillGutyrchik commented on src/TechObject/ObjectsTree/UniversalObject/Actions/GroupableAction.cs
> +            parameters = new List<BaseParameter>();
Изменил, теперь все в ActionToStepByCondition.

2022-03-29 09:38 UTC, idzm approved these changes

2022-03-29 09:38 UTC, merged