[review]Bug fixed
savushkin-r-d/EasyEPLANner pull request #996
Opened 2022-04-01 09:42 UTC by VadimZezyotkoATP

2022-04-05 12:07 UTC, idzm requested changes

2022-04-05 12:07 UTC, idzm commented on docs/user_manual/ReadMe.md
> +Если после завершения тестирования появилась ошибка (**Не найден кабель AODOAIDI**), нужно предпринять следующие действия:
```suggestion
Если после завершения тестирования появилась ошибка (**Не найден канал AODOAIDI**), нужно предпринять следующие действия:
```

2022-04-05 12:15 UTC, AlexandrBehunkov commented on docs/user_manual/ReadMe.md
> +2. **В этом же пункте необходимо синхронизировать название устройств и модулей.**
```suggestion
2. **В этом же пункте меню выбираем необходимо выбрать синхронизация названий устройств и модулей .**
```

2022-04-08 08:31 UTC, idzm approved these changes

2022-04-08 08:31 UTC, idzm approved these changes

2022-04-08 08:32 UTC, merged

2022-04-08 08:32 UTC, AlexandrBehunkov approved these changes